dbt_project:
  outputs:
    dev:
      account: CPYPVRL-FC01651
      database: dbt_hol_2025_dev
      password: Sub@ru007007007
      role: dbt_hol_role_dev
      schema: public
      threads: 100
      type: snowflake
      user: dbt_hol_user
      warehouse: vwh_dbt_hol_dev
    prod:
      account: CPYPVRL-FC01651
      database: dbt_hol_2025_prod
      password: Sub@ru007007007
      role: dbt_hol_role_prod
      schema: public
      threads: 100
      type: snowflake
      user: dbt_hol_user
      warehouse: vwh_dbt_hol_prod
  target: dev
